### ISSUE TITLE
undertaker-registry needs to be updated to 0.0.3

### ISSUE THREAD

**Issue by mattgoldspink** [ng-tools/ng-factory#7]
At the moment the build of ngStrap consistently fails with:

```
10:59:57] Found 1 undertaker-registry to load with ng-factory
[10:59:57] Using ng-factory config file ~/development/angular-strap/ngfactory.json

AssertionError: Custom registry must have `init` function
    at validateRegistry (/Users/matt/development/angular-strap/node_modules/gulp/node_modules/undertaker/lib/helpers/validateRegistry.js:28:5)
    at Gulp.registry (/Users/matt/development/angular-strap/node_modules/gulp/node_modules/undertaker/lib/registry.js:18:3)
    at ngFactory (/Users/matt/development/angular-strap/node_modules/ng-factory/lib/index.js:37:9)
    at Function.ngFactory.use (/Users/matt/development/angular-strap/node_modules/ng-factory/lib/index.js:65:37)
    at Object.<anonymous> (/Users/matt/development/angular-strap/gulpfile.js:5:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by mattgoldspink** [comment]
Sorry - my bad. It looks like what I cloned in ngStrap isn't up to date properly.The ng-factory repo is correct.
